### ISSUE TITLE
EZBlocker stuck in state "Loading..."

### ISSUE THREAD

**Issue by Niehztog** [Xeroday/Spotify-Ad-Blocker#100]
since a few days EZBlocker (latest Version 1.6.8.2) shows the message "Loading..." in the main window (See screenshot).
![unnamed](https://cloud.githubusercontent.com/assets/191015/19829034/06951af6-9dd7-11e6-84ef-745625d65fb8.png)

Furthermore a logfile appears in the same path as `EZBlocker.exe`. Its called `EZBlocker-log.txt` and containes the following message multiple times: `The remote server returned an error: (403) Forbidden.`
It seems the longer EZBlocker is running, the more the logfile grows. It repeatedly appends the above error message to the logfile.

I guess it tries to update its blocklist from a remote server, which is no longer available.

**Comment by Xeroday** [comment]
Has EZBlocker worked for you in the past? And have you tried restarting Spotify/your computer?

**Comment by Niehztog** [comment]
Yes it worked but last time I used it was one year ago and it was an older version. My Sophos Antivirus might block the HTTP requests. I have to verify. Is there an URL/Hostname I can unblock in my Antivir?

**Comment by Niehztog** [comment]
My Sophos Antivirus seems to be involved. It appears as soon as I start EZBlocker it downloads the file "nircmd.exe", which my Sophos recognises as "Adware/PUA" and is therefore blocked. IS there a workaround?

**Comment by sakshamgoyal01** [comment]
allow the file to be downloaded???? download it manually?

**Comment by FireEmerald** [comment]
NirCmd is a small command-line utility that allows you to do some useful tasks without displaying any user interface. Do not trust everything what your anti-virus suite tells you.
Download: http://www.nirsoft.net/utils/nircmd.html

**Comment by kjacewicz** [comment]
EZBlocker controls Spotify Client using random address from domain spotilocal.com, which all points to 127.0.0.1.
Maybe you are behind web proxy ? Try add *.spotilocal.com to system proxy exception list.

**Comment by Rsslone** [comment]
I too am having a issue but I don't have any third party AV software installed. I had a company private AV installed for a couple days but it has since been removed.

**Comment by mran3** [comment]
I am having same problem, log says: spotilocal.com:
The remote name could not be resolved: '63888434.spotilocal.com'The remote name could not be resolved: '63888434.spotilocal.com'

**Comment by jonruhnke** [comment]
1.6.8.4 does not work for me on Windows 10. The bottom of the program is stuck on "Loading...". The log file is spammed with "The remote name could not be resolved: '88748596.spotilocal.com'".

1.6.8.0 works just fine, aside from the last second of ads sometimes playing.

**Comment by kjacewicz** [comment]
In version 1.6.8.2 local address of Spotify service has changed from "http://127.0.0.1" to "https://" + hostname + ".spotilocal.com" (EZBlocker/EZBlocker/WebHelperHook.cs line 158).
It caused connection problem on machines connected to internet over webproxy - connection from Adblocker to Spotify app goes now to webproxy, instead of staying on local machine.
As workaround, add *.spotilocal.com to system proxy exception list, or use version 1.2.8.0.

**Comment by jfonte** [comment]
Q: does the latest pre-compiled binary include #108 ? Cheers.

**Comment by Xeroday** [comment]
Newest version should resolve this.
