### ISSUE TITLE
win10 notifications repeats after closing spotify

### ISSUE THREAD

**Issue by AntIR** [Xeroday/Spotify-Ad-Blocker#101]
After closing Spotify, windows 10 action center repeats a notification with the message: "Spotify not found please restart Spotify." Other than that this program works great!

**Comment by AndrewKirkovski** [comment]
Can confirm, I have same issue

**Comment by Xeroday** [comment]
Does it say restart or does it say "Spotify not found, exiting EZBlocker."?

**Comment by AntIR** [comment]
Thank you very much!
