### ISSUE TITLE
Analytics opt-out

### ISSUE THREAD

**Issue by danielchalmers** [Xeroday/Spotify-Ad-Blocker#103]
Would be great to be able to opt-out of analytics reporting.
Ideally with the other check boxes.

**Comment by FireEmerald** [comment]
@danielchalmers  Just comment out this try catch block, and you are opted-out: [Form1.cs#L358](https://github.com/Xeroday/Spotify-Ad-Blocker/blob/master/EZBlocker/EZBlocker/Form1.cs#L358)

**Comment by danielchalmers** [comment]
Is there any reason to not have it as an option?

**Comment by Xeroday** [comment]
The same reason there's no media buttons on the app -- takes too much space, especially since it's a one time thing and would never be toggled. Feel free to fork the code and remove it yourself or block the Google analytics domain in your hosts file.
