### ISSUE TITLE
New Feature: Write current song name to file

### ISSUE THREAD

**Issue by Marty** [Xeroday/Spotify-Ad-Blocker#106]
Hi,
the option to have the currently played song written to a file would be pretty cool to show it with OBS for example.
Other tools are already capable of that, but everything in one handy tool, would be nice :)

**Comment by MrLabRat** [comment]
you can do this with Snip -> https://github.com/dlrudie/Snip/releases/tag/v6.9.1

**Comment by Xeroday** [comment]
I don't plan on adding features not related to ad-blocking to this project. Sorry.
