### ISSUE TITLE
Ad plays when Spotify is hidden by a Virtual Desktop Manager

### ISSUE THREAD

**Issue by roydukkey** [Xeroday/Spotify-Ad-Blocker#11]
If using a virtual desktop manager (VDM), ads will not be blocked while Spotify window is hidden by VDM.

1. If the Spotify window is shown during an ad, EZBlocker will recognise the an ad and block it.

2. Should the window be hidden while an ad is being blocked, EZBlocker will not resume playing music until Spotify is shown by vdm.

I have tested Dexpot and VirtuaWin and have verified the issue appears with both of these VDM.

**Comment by Xeroday** [comment]
Should be completely fixed in EZBlocker 1.5 for Spotify 1.0.1+.
