### ISSUE TITLE
Ads play for the last second

### ISSUE THREAD

**Issue by Phoenixalibur** [Xeroday/Spotify-Ad-Blocker#112]
The mute feature works without fail every time, except that it un-mutes ads for the last second. This makes a bad transition from silence into music.

This happens to me with a fresh install of Spotify (1.0.53.758.gde3fc4b2) with the default options, and the default options for EZBlocker (v1.6.8.4). This error was found on Windows 10.

The ad says 0:30 of 0:30 when I hear the noise. This could probably be fixed by waiting a little longer once the ad is complete.

**Comment by FireEmerald** [comment]
Note that this doesn't appear **always**. It's a **rare phenomenon** which happens for me with about ~5% of the muted ads. Most of the tracks are muted correct.

**Comment by Phoenixalibur** [comment]
I notice it happening very often. Maybe only certain ads have a sound at the very end. Regardless, this is still a problem that many users notice.

**Comment by Phoenixalibur** [comment]
It sounds like it is a basic enough rule that it could be a user option instead of hard-coded.

**Comment by Xeroday** [comment]
New version should wait a little bit longer before ads are unmuted.
