### ISSUE TITLE
[Tweak] Kill Spotify process when updating

### ISSUE THREAD

**Issue by Evolution0** [Xeroday/Spotify-Ad-Blocker#120]
When a new version of EZBlocker is available we get a handy notification and the option to visit the site and grab the latest version, this is great. The issue lies in the fact that Spotify still launches.

Its a minor annoyance (More so on slower systems though) that can hopefully be fixed by either doing the version check *before* launching Spotify and not launching at all if the option to update is chosen or force killing the process if a user chooses to update now (and be redirected to the site)

**Comment by MatrixDJ96** [comment]
Check ezblocker 2

**Comment by Xeroday** [comment]
Will consider disabling Spotify auto-launch on future versions.
