### ISSUE TITLE
[Feature Request] Add option to start minimized

### ISSUE THREAD

**Issue by Ammar-Dayoub** [Xeroday/Spotify-Ad-Blocker#123]
My request is a 4th checkbox to add the option of starting the program with full functionality but it'll be minimized to system tray.

by "full functionality" I mean when you start EZBlocker, it will start EZBlocker service minimized along with Spotify

something like this
```
If My.Settings.StartMinimized Then
    WindowState = FormWindowState.Minimized
End If
```

**Comment by MatrixDJ96** [comment]
Done in my version:)

**Comment by Sogolumbo** [comment]
This feature already is kind of implemented: If your EZBlocker is minimized and you exit EZBlocker in the Taskbar and start it again it will restart minimized. 
PS: To make sure that the user won't be annoyed by unnecessary Notifications I created a version which will only notify you the first time you minimize the app. I have started a pull request for that version.

**Comment by Xeroday** [comment]
I don't want too many checkboxes in the app. If you enable "Start EZBlocker on Login", EZBlocker will auto-start in the tray.
