### ISSUE TITLE
crashes on 32bit systems

### ISSUE THREAD

**Issue by Sogolumbo** [Xeroday/Spotify-Ad-Blocker#125]
I want to use this Program on my 32bit Windows 10 tablet/laptop.
The program works on my 64bit PC (that's where I'm running Visual Studio).
At the first try I compiled the program (without making any changes) and copied the files to the laptop. Running it did not work (as expected) because I compiled it on a 64bit machine.
At the second try I chose the x86 target platform in both projects. But the program program crashed on both my PC and laptop: 
![error message](https://user-images.githubusercontent.com/33571916/33509635-85e15584-d703-11e7-8366-3191ce6f389e.PNG)
(It says: EZBlocker stopped working.... Debug/Close)
I tried debugging it but I have not found out, what the problem is.
All I found out is that the crash is shortly after the `Marshal.ThrowExceptionForHR(_AudioSessionManager2.RegisterSessionNotification(_AudioSessionNotification));` method call (line 62 in AudioSessionManager2.cs). I am really unexperienced in debugging outside of managed Code (C#) and VisualStudio Projects (self-written code).
I hope someone else can solve this Issue.

**Comment by MatrixDJ96** [comment]
Check ezblocker 2

**Comment by Xeroday** [comment]
Seems like an issue with the finding the audio drivers. Can you try the latest version and let me know if you still have a problem?

**Comment by Sogolumbo** [comment]
It didn't crash until I checked the option: "Block Banner Ads". It kept crashing at every startup.
I reset the option in the settings file and now it's working again (Muting Ads as it is supposed to do).

**Comment by Xeroday** [comment]
That issue you just had is unrelated to 32 bit systems and has been fixed in 1.7.1.1. 

Let me know if the latest version still crashes.
