### ISSUE TITLE
EzBlocker opens Spotify automatically

### ISSUE THREAD

**Issue by starikcetin** [Xeroday/Spotify-Ad-Blocker#127]
Give us an option to disable this behaviour, please. I only want the EzBlocker to launch at the start, but not the Spotify.

**Comment by MatrixDJ96** [comment]
Check ezblocker 2

**Comment by Xeroday** [comment]
Will consider in a future release. It used to be required for EZBlocker to read Spotify properly, but not now.

Thanks for the feedback.
