### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by MLZ91** [Xeroday/Spotify-Ad-Blocker#130]
I would really like, if your blocker could skip some artists (for example Bieber ;P)

I dont think this would be very hard to implement and propably many would enjoy this feature :)

**Comment by janwiebedroid** [comment]
Hi, i made an addin that does exactly that :-) 
https://github.com/janwiebedroid/SpotifyBlocker

**Comment by MLZ91** [comment]
Great thanks, will check it out! :)

Mit freundlichen Grüßen,
Milos Ziolkowski

Von: janwiebedroid
Gesendet: Samstag, 23. Dezember 2017 12:12
An: Xeroday/Spotify-Ad-Blocker
Cc: MLZ91; Author
Betreff: Re: [Xeroday/Spotify-Ad-Blocker] Feature request (#130)

Hi, i made an addin that does exactly that :-)
https://github.com/janwiebedroid/SpotifyBlocker

**Comment by Xeroday** [comment]
Out of scope for this project.
