### ISSUE TITLE
Prevents Spotify taskbar thumbnail preview from having playback controls

### ISSUE THREAD

**Issue by vith** [Xeroday/Spotify-Ad-Blocker#137]
![spotify](https://user-images.githubusercontent.com/3265539/39517869-d4cb7078-4dc6-11e8-8c88-ba5c71c22351.png)

This only happens when Spotify is launched by EZBlocker. If I open it myself the playback controls will be present.

![image](https://user-images.githubusercontent.com/3265539/39517933-01e7ac20-4dc7-11e8-9f24-fb0d3f00fb40.png)

**Comment by Xeroday** [comment]
I'm not able to replicate this. Can you try the latest EZBlocker version and let me know if you're still having this issue?

**Comment by vith** [comment]
Still happens on v1.7. Looks like launching it as Administrator is what triggers it--without that the controls show up. I'm also affected by #146 on the new version for what it's worth.

**Comment by Xeroday** [comment]
Looks like it's not related to EZBlocker. If you keep EZBlocker closed and open Spotify as administrator, the controls still won't show.

Once you've enabled "Block Banner Ads" once, you can run EZBlocker as a non-administrator and it'll work just fine. That way, it'll launch Spotify as a normal user.

**Comment by vith** [comment]
> Once you've enabled "Block Banner Ads" once, you can run EZBlocker as a non-administrator and it'll work just fine.

Good to know, I'll do that.

Maybe you can drop the Administrator permissions when launching spotify? Looks like [the Windows API is annoying](https://stackoverflow.com/questions/11169431/how-to-start-a-new-process-without-administrator-privileges-from-a-process-with), but there are some libraries for it.

i.e. `UACHelper.StartLimited()` from https://github.com/falahati/UACHelper

or vice versa: launch a subprocess to do the "Block Banner Ads" stuff in a way that uses an interactive UAC prompt.
