### ISSUE TITLE
EZBlocker Not allowing friend feed to load

### ISSUE THREAD

**Issue by buboniclantern** [Xeroday/Spotify-Ad-Blocker#138]
I’m having issues with EZBlocker blocking my friend’s activity feed. When Spotify launches with EZblocker running the Friend Feed won't load. If I uncheck "Disable All Ads (Experimental)" and select "Try Again" under Friend Activity it'll reload. If EZBlocker is executed after Spotify has already been running the feed won't update, the Friend Feed will instead show the last known activity of my friend's activity before EZBlocker/Disable All Ads was turned on. This previously wasn't an issue and possibly started being an issue following a Spotify update, though I'm not sure which update. I've been experiencing this issue for a couple weeks now.

Spotify Version: 1.0.80.474.gef6b503e
EZBlocker Version: 1.6.8.6
![friendactivityfeed](https://user-images.githubusercontent.com/39129572/39822923-dce22c1c-5379-11e8-9077-4c63404f5b35.jpg)

**Comment by kevindalmeijer** [comment]
I would like to report the same problem. Additionally, the daily mixes cannot be used when "Disable all adds" is enabled.

Spotify Version: 1.0.83.318.g6c07039d
EZBlocker Version: 1.6.8.6

**Comment by franomai** [comment]
@kevindalmeijer, how did you downgrade the Spotify version?

**Comment by kevindalmeijer** [comment]
@franomai Simply uninstall the current version (via control panel) and download the full installer of an older version at Filehippo. For example: [version 1.0.70.388](https://filehippo.com/download_spotify/80653/).

**Comment by blackwhattack** [comment]
Is it going to auto-update? That was my experience previously, but I don't know how to turn it off.

**Comment by Xeroday** [comment]
I've updated EZBlocker to 1.6.9. Has this issue been resolved?

**Comment by franomai** [comment]
Hey @Xeroday, it doesn't look like anything has changed.

Maybe someone else can verify, or how can I confirm the app I am currently running? Just looking at the code, I assume you changed this line, but my hosts file hasn't updated https://github.com/Xeroday/Spotify-Ad-Blocker/blob/master/EZBlocker/EZBlocker/Form1.cs#L34

Furthermore, I don't believe this will fix the issue, as raised in this ticket.https://github.com/Xeroday/Spotify-Ad-Blocker/issues/140

**Comment by AmperAndSand** [comment]
I found that the last version that would have ads blocked with EZBlocker while still keeping Radios, Daily Mix and Friend Activity working is [Spotify 1.0.80.474](https://filehippo.com/download_spotify/84258/). See the post above by kevindalmeijer to know how to edit the HOSTS file to prevent Spotify from updating to the latest version.

**Comment by Xeroday** [comment]
Newest EZBlocker shouldn't interfere with this anymore. I'd suggest [clearing your hosts file](https://support.microsoft.com/en-us/help/972034/how-to-reset-the-hosts-file-back-to-the-default) if you're still having issues.
