### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [Xeroday/Spotify-Ad-Blocker#139]
In the last couple of days, I've observed this for EZBlocker.exe in my task manager:

```
Day 1
20:00 - 16 MB
23:30 - 17 MB

Day 2
12:25 - 26 MB
17:00 - 29 MB
00:00 - 31 MB

Day 3
12:33 - 38 MB
22:30 - 48 MB

Day 4
12:15 - 52 MB
```

**Comment by Xeroday** [comment]
I rewrote a lot of EZBlocker for v1.7, which should help with this. Please create a new issue if it's still happening.
