### ISSUE TITLE
EZBlocker detected as Win32/Zpevdo.A by Windows Defender

### ISSUE THREAD

**Issue by franomai** [Xeroday/Spotify-Ad-Blocker#141]
![image](https://user-images.githubusercontent.com/9399879/42002235-9d1be79a-7aba-11e8-88d3-41ca0a6b95c0.png)

Only happened with the new version. VirusTotal result here.

https://www.virustotal.com/#/file/f84d227275ef18fa572dbd8238bdd1d391f02915dee9efdfd17d4e3abc105315/detection

I'm not concerned that it's actually a virus, just wondering what changed to raise this flag.

EDIT: I assume it's getting flagged because of the use of NirCmd, but the old version also used it, so as before I don't know why it's only picking it up now. Maybe because this new version isn't signed, so it's being marked as higher risk?

**Comment by fuhrmanator** [comment]
I'm guessing it's not the signature as much as it's being cautious (nobody's vouched for it?).

**Comment by fuhrmanator** [comment]
Virustotal says it's clean: 

https://www.virustotal.com/#/url/071185ec672d3c059ccfbee748570521b81b091bf02a2c8cc3ae771a13c3c1ff/detection

**Comment by fuhrmanator** [comment]
Not great results from Jotti.org (5/16 scanners find malware, e.g., NirCmd, NirCmd2, etc.):

https://virusscan.jotti.org/en-US/filescanjob/g6jjx16wr2

**Comment by abhijithvijayan** [comment]
same for Kaspersky total security

**Comment by thepcwiz101** [comment]
i dont get any notifications of any viruses. i use avast free antivirus.

**Comment by Mysame** [comment]
Windows 10 version 1803 was also very unhappy about the file. Had to unblock it and everything.

**Comment by thepcwiz101** [comment]
smart screen is to blame. it happens on tons of files. it has to do with a signature or something.

**Comment by anthony-wang** [comment]
For me, it wasn't blocked by Windows (build 1803), but by Comodo Firewall 10 (version 10.2.0.6526). Unfortunately, it doesn't give any details as to why it decided to block it (not in the logs either). It just says "blocked by auto-containment".

**Comment by thepcwiz101** [comment]
Virustotal is now detecting this as a virus. its detected as a trojan horse by quite a few antivirus products. even hitman pro detects it as a virus.

**Comment by Xeroday** [comment]
Latest version updated to remove external dependencies.

https://www.virustotal.com/#/file/522b685dd829bbbab0143a2b8fc1fbcc2f9ccb6cd8a40650d0d8fa23e96b5ec4/detection
