### ISSUE TITLE
no longer detect, that spotify is playying

### ISSUE THREAD

**Issue by CzBuCHi** [Xeroday/Spotify-Ad-Blocker#144]
tested on spotify: V 1.0.62.508, 1.0.72.117,  1.0.85.257

EDIT:
windows version: 10.0.17134.165
EZBlocker 1.6.8.6 (signed 31 August 2017 22:29:23)

**Comment by DefecateRainbows** [comment]
Same here, it just says Spotify is paused.

**Comment by pholt** [comment]
Getting this issue as well. Spotify version: 1.0.85.259.g4ab01679

**Comment by CzBuCHi** [comment]
just checked another pc and here it is working (showing "playing Adele" right now ...)
spotify version: 1.0.84.344.gfc674f6f
windows version: 10.0.17134.165
EZBlocker 1.6.8.6 (signed 31 August 2017 22:29:23)

at evening i will add ez and win versions to my first comment...

**Comment by sthy14** [comment]
I guess the token url: https://open.spotify.com/token no longer works as it says fake token: 
{"t":"NAowChgKB1Nwb3RpZnkSABoGmAEByAEBJRkS1lUSFChLvW4mGdnft8WUvRy**faketoken**"}

**Comment by dissovldgrl** [comment]
mine is also saying Spotify is paused when it is not.
Windows 10 version 1709
Spotify version 1.0.85.259
EZ Blocker 1.6.9.0

Previous version of EZBlocker did the same.

**Comment by DefecateRainbows** [comment]
EZBlocker2 fails with a similar OAuth error. How would one go about getting a new token?

**Comment by Xeroday** [comment]
Looks like Spotify shut down their API yesterday... https://developer.spotify.com/community/news/2018/07/19/new-updates-to-spotify-play-button/

I'll be spending some time rewriting EZBlocker to adapt, but ETA might be a bit longer. My best suggestion right now is to revert to an older version of spotify.

**Comment by CzBuCHi** [comment]
just an idea: convert ezblocker to http proxy that spotify will use - then intercept ads requests and mute spotify for 30 seconds (fiddler is somehow able to intercept https requests, so it is doable ...)
this makes ezblocker independent on spotify update ...

**Comment by Xeroday** [comment]
Version 1.7 is now compatible with the latest version of Spotify.
