### ISSUE TITLE
Spotify Issued Ads not blocked x2

### ISSUE THREAD

**Issue by franomai** [Xeroday/Spotify-Ad-Blocker#145]
Hi @Xeroday,

Just so you are aware, with the new version (1.7) -

a) Spotify Issued Ads (upgrade to premium today! look at this playlist!) are not blocked - the ad plays
b) When these ads are playing, some of them are no longer muted.

![image](https://user-images.githubusercontent.com/9399879/43052612-883ea824-8e7b-11e8-90b7-535ccfbbc047.png)

This is on most recent version. Friend feed and such is back.
Any ideas? I realise a) is hard to fix with just hosts but maybe something can be done for b)? If I can help at all let me know.

Thanks.

**Comment by Xeroday** [comment]
Thanks for the issue report -- interesting edge case I didn't run into in my testing. The newest version (1.7.1) should fix it.
