### ISSUE TITLE
EZBlocker does not load when Spotify is not loaded.

### ISSUE THREAD

**Issue by kevindalmeijer** [Xeroday/Spotify-Ad-Blocker#146]
@Xeroday thank you for the 1.7 update, it is much appreciated! The new version seems to work great, but I did run into the following bug.

If Spotify (v1.0.85.259.g4ab01679) is not loaded and I start EZBlocker (v1.7, administrator priviliges), then EZBlocker states "Loading:" and then exits without any message. The problem persists when "Start Spotify with EZBlocker" is ticket. If first Spotify is started manually, then EZBlocker works as expected.

OS: Windows 10 Home 1803 build 17134.165.
Antivirus: Windows Defender, with the EZBlocker folder whitelisted. The first time running v1.7 Windows Defender Smartscreen gives a warning, which I ignored, and it has not returned.

**Comment by Xeroday** [comment]
Thanks for reporting, fixed this in 1.7.1.1.
