### ISSUE TITLE
Ezblocker switch to muted mode when spotify is paused then resume music on its own (v1.7)

### ISSUE THREAD

**Issue by DavidGGs** [Xeroday/Spotify-Ad-Blocker#147]
Steps to reproduce this behavior :
1. Launch spotify
2. launch EZBblocker
3. Play some music (EZBlocker display "playing:...")
4. Pause Spotify

**Result** : EZBlocker doesn't display "spotify is paused" but "muting : spotify" instead

If you wait (same delay as for ads), EZBlocker will resume Spotify

*Note : I use Spotify app from Windows Store : 1.0.85.259.g4ab01679*

**Comment by sthy14** [comment]
I'm having this problem when I pressed the pause on the keyboard. However, if I click the pause button in Spotify it will pause correctly. 

Spotify version: 1.0.85.259.g4ab01679
OS: Win10 10.0.16299
Ezblocker: master branch

**Comment by Xeroday** [comment]
Thanks for reporting this. 1.7.1.1 should allow you to pause.
