### ISSUE TITLE
Version 1.7 keeps playing current track unprompted

### ISSUE THREAD

**Issue by thatguy344** [Xeroday/Spotify-Ad-Blocker#149]
Hello! As the title says, i just downloaded the newest version of EZBlocker and while it does seem to start up noticeably faster it keeps resuming the client's current track (if it's paused that is) every 5-10 seconds or so, even when the client is completely in the background. I noticed the desktop icons also start refreshing around the same time when this happens. Right now i had to roll back to the previous stable version that worked flawlessly for me due to this. Will this bug be fixed soon?

**Comment by Xeroday** [comment]
Are you on 1.7 or 1.7.1.1?

**Comment by EnzoDevelop** [comment]
I can confirm this issue on latest version seems as though EZ blocker thinks the paused song is an ad
https://screenshot.enzodevelopment.ml/f/XV4pcHe7.gif

**Comment by Xeroday** [comment]
I've updated EZBlocker again and changed the way it detects ads. Let me know if this issue comes up again.
