### ISSUE TITLE
Doesn't work when Spotify is minimized to taskbar

### ISSUE THREAD

**Issue by Woodahs** [Xeroday/Spotify-Ad-Blocker#150]
If Spotify is minimized to taskbar, then EZBlocker doesn't seem to work. EZBlocker is just showing "Spotify is pauzed". Once I get Spotify window to the foreground, all is working fine
Version used for tests: 1.7.1.2

**Comment by GenesisFR** [comment]
@Xeroday I'd recommend using something like https://gist.github.com/GenesisFR/de0ad5710fb5eb221b5a239e819728bf to get the window handle of Spotify (last time I checked, it was always index 0 in the list) as processs.MainWindowTitle is equal to IntPtr.Zero when Spotify is sitting in the taskbar.

**Comment by Xeroday** [comment]
I'm able to grab the handle, just not the window title. The latest version should work even when Spotify is minimized to tray. It won't be able to tell what the artist is, but it will know if an ad is playing.
