### ISSUE TITLE
v1.7.1.2 - Concerts - "There was error requesting data"

### ISSUE THREAD

**Issue by moodyswing** [Xeroday/Spotify-Ad-Blocker#151]
Spotify with ezblocker v1.7.1.2  on will not display any concerts data, both on Browse -> Concerts tab ("There was error requesting data") and given artist concerts page ("Something went wrong. Try again later").

**Comment by moodyswing** [comment]
Yes, I have it enabled.

**Comment by Xeroday** [comment]
Seems to be working. You might want to clear your hosts file if you've been trying to patch Spotify ads from other guides.

![image](https://user-images.githubusercontent.com/867467/43187198-a7fafa8e-8fa5-11e8-8d1c-e1feac7e36f1.png)
