### ISSUE TITLE
Bug: "Start Spotify" Option Results in Second Instance

### ISSUE THREAD

**Issue by Chiramisu** [Xeroday/Spotify-Ad-Blocker#155]
EZBlocker Version: 1.7.2.5
Spotify Version: 1.0.86.337

When the "Start Spotify with EZBlocker" option is selected (as is the default), and Spotify is already running, EZBlocker will cause the running instance of Spotify to crash and relaunch. This has the additional side effect of causing Spotify to lose its place and revert back to a previous state; even a previous playlist or song.

**Comment by Xeroday** [comment]
The Spotify restart isn't due to that option. It's b/c EZBlocker needs to patch Spotify and will restart it. Should only happen when it's your first time opening EZBlocker or when Spotify updates.
