### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Eddi2015** [Xeroday/Spotify-Ad-Blocker#156]

**Comment by EnzoDevelop** [comment]
have you tried using WiNE

**Comment by Eddi2015** [comment]
No, but I bet it isn't going to work

**Comment by EnzoDevelop** [comment]
you should try it

**Comment by Eddi2015** [comment]
Actually I found AdKiller (https://github.com/SecUpwN/Spotify-AdKiller). I'm using it and it works perfectly.
