### ISSUE TITLE
Bug: Song Detection Fails when Spotify Minimized to System Tray

### ISSUE THREAD

**Issue by Chiramisu** [Xeroday/Spotify-Ad-Blocker#158]
EZBlocker Version: 1.7.2.5
Spotify Version: 1.0.86.337

Doesn't show "Playing" track when Spotify is minimized to the System Tray. It only successfully displays the playing track when Spotify is at most minimized to the Taskbar, and not when fully minimized to the System Tray.

**Comment by Xeroday** [comment]
The song detection won't work, but it should still block ads. Closing this now as it's expected behavior.
