### ISSUE TITLE
Pause a song then 30 seconds later it stats playing again by itself.

### ISSUE THREAD

**Issue by Botnary** [Xeroday/Spotify-Ad-Blocker#162]
There is no way to pause Spotify songs, since EZBlocker will start playing it again after exactly 30 seconds.
It scared me one night, i usually leave my computer running for days, i put Spotify on pause and went to bed, then the music started playing 30 seconds later )) 

EZBlocker  v1.7.2.5
1.0.86.337.ga8d5cef9 (Windows Store version)

**Comment by Xeroday** [comment]
Windows store version is not supported, as explicitly mentioned on the project site and when you start EZBlocker.

**Comment by goalie7960** [comment]
I should have added I have this problem too with the windows version I downloaded directly from github.

v1.7.1.2
