### ISSUE TITLE
EZ-Blocker no longer working with latest version of Spotify in Windows 10.

### ISSUE THREAD

**Issue by bkraul** [Xeroday/Spotify-Ad-Blocker#164]
Latest available version of EZ-Blocker (1.7.2.5) no longer works with the latest downloadable version of Spotify (1.0.87.491.ge2a121fc).

The follwing message pops up:
![image](https://user-images.githubusercontent.com/14616851/43913372-6899c0ce-9bca-11e8-9b85-2ba4c6d1e75b.png)

When the OK button is clicked, the version that is downloaded and installed is the same version as above, which in turn leads EZ-Blocker to come back again with the same message.

From looking closer at the version that is installed by clicking on the OK button is now the Windows Store Version. Apparently Spotify has unified their app and confined it to only the AppStore (WUP) application.

**Comment by moodyswing** [comment]
+1. Even if full package is downloaded, Windows will migrate everything to store version anyway.

**Comment by bluegrams** [comment]
I'm actually using the same version of Spotify (1.0.87.491.ge2a121fc) and EZBlocker but it works perfectly for me.

**Comment by 0xL33t** [comment]
Using an even newer Spotify Version (1.0.88.353.g15c26ea1) and I get the "Patching Spotify" Error

**Comment by danidini** [comment]
![image](https://user-images.githubusercontent.com/34184001/44664046-53790580-aa3c-11e8-9f6a-32db9aeb5fcc.png)
how to fix net framework error?
