### ISSUE TITLE
Add EZBlocker to chocolatey packages

### ISSUE THREAD

**Issue by mjarkk** [Xeroday/Spotify-Ad-Blocker#165]
For installing programs on windows i use [Chocolatey](https://chocolatey.org/) but i couldn't found you're package there.  
Do you have any plans to add it to the Chocolatey.

**Comment by beppe9000** [comment]
this is a grey-zone project, I doubt it would be beneficial to have it on choco

**Comment by mjarkk** [comment]
Ya that's true i'll close this issue for now i don't think it would be used by many people
