### ISSUE TITLE
HTTP Request spaming localhost:19691 - Suggestion

### ISSUE THREAD

**Issue by CzBuCHi** [Xeroday/Spotify-Ad-Blocker#166]
these two urls: **http://localhost:19691/true** and **http://localhost:19691/false**
from code it seems that spotify process  is spamming this url to tell ez if ad is running or not  ...
any chance that u can send request only on state change? - basically modify your worker.js:

```diff
+var _p;
var sendEZB = function(e) {
+    if (_p === e) return;
+    _p = e;

    var t = new XMLHttpRequest;
    t.open('GET', 'http://localhost:19691/' + e, true);
    t.send();
};

self.addEventListener('message', function(e) {
    sendEZB(e.data);
    setTimeout(function() { postMessage('ready'); }, 300);
}, false);
```

I could create PR for this, but that too much work for 30 chars of code :)

PS: Feel free to close this after reading it and never send response :) - i dont mind

**Comment by tsarpaul** [comment]
My client was lagging after installing the ad blocker (old computer), adding this solved the problem.

**Comment by beppe9000** [comment]
My interception proxy got spammed by this during debug of a web app xD

**Comment by CzBuCHi** [comment]
> My interception proxy got spammed by this during debug of a web app xD

fiddler? exactly why i added this issue ...

**Comment by beppe9000** [comment]
Yeah! Altough you should be able to ignore requests made to localhost in the settings, I found useful to setup a FiddlerScript filter to hide requests from the exe file, in case the server you are debugging is also on localhost.

**Comment by Xeroday** [comment]
Newest EZBlocker no longer uses this mechanism.
