### ISSUE TITLE
Uninstall EZBlocker

### ISSUE THREAD

**Issue by martonlente** [Xeroday/Spotify-Ad-Blocker#182]
Hello,

EZBlocker doesn't come with an installer, but works after running the file. Interestingly, though my Spotify keeps not playing ads after removing the file from my computer – like if EZBlocker were still present behind the scenes. **Is there a way to actually force uninstall EZBlocker?** If so, how?

Note: I don't see EZBlocker on my taskbar, neither in Task Manager. My EZBlocker was set to start with Windows. I'm on Windows 10. I'm using the Spotify UWP app (which I've also tried resetting).

Thank you in advance,
Márton Lente

**Comment by FireEmerald** [comment]
Open your `%windir%\System32\drivers\etc\hosts` file with an text editor as administrator and remove any line which contains one of the following urls:

https://github.com/Xeroday/Spotify-Ad-Blocker/blob/88acf24684c1b260f6715d2de2be87bd15412029/EZBlocker/EZBlocker/EZBlockerMain.cs#L27

**Comment by martonlente** [comment]
Thanks @FireEmerald, it perfectly worked.

**Comment by Masterface1** [comment]
Hi, I dont have the permissions to change it how do i get those???

**Comment by yassin97** [comment]
> Hi, I dont have the permissions to change it how do i get those???
> i can open it as a administrator.
Hi @Masterface1,
make a copy, change it, then replace it in the folder as an administrator.

**Comment by yassin97** [comment]
Hi @Masterface1 ,
make a copy, change it, then replace it in the folder as an administrator.

**Comment by WorldofLoina** [comment]
Just want to earmark this for anyone suffering from spotify not being able to stream songs and only showing local files, if you're using ezblocker @FireEmerald's solution solved it for me.

**Comment by naydenjguyen2102** [comment]
for some reason i cant see anything about spotify when I open %windir%\System32\drivers\etc\hosts plz help
