### ISSUE TITLE
EZBlocker stopped working again after last update?

### ISSUE THREAD

**Issue by thatguy344** [Xeroday/Spotify-Ad-Blocker#184]
So when i opened Spotify today it loaded a very small patch and although i could play a track for a minute or so the program then crashed with the usual "stopped working" message (I had to log off for it to even react and then it also said "The application was unable to start correctly") all of a sudden and has not been working properly ever since, with Ezblocker or without. 

Now whenever i open Spotify up i am greeted by the blank grey client window but without any stuff in it. I already tried deleting/refreshing appdata folders but then it says "Spotify is not installed or you have the store version".

What's also weird is that ever since this patch there's four (!) Spotify.exe processes starting up every single time now, afaik it never behaved like this before so it musta been introduced with their new patch aimed specifically (yet again) at hindering the functionality of EZBlocker. I will try to replicate this on another computer but in the meantime i thought it prudent to ask whether anyone else has been experiencing issues like this after the newest patch

- Regards

**Comment by LearningMonkey** [comment]
Same issue since this morning. Blank window.

**Comment by thatguy344** [comment]
> 
> 
> Same issue since this morning. Blank window.
> 
> Restarting Spotify doesn't help, even after closing EZBlocker - reinstalling is the only fix.

I tried reinstalling but as soon as you start Spotify via EZBlocker the empty window issue reappears again... I also noticed that the Spotify folder seems to be entirely absent from the Programs folder, it seems like with this recent new patch they moved the entire thing over to AppData completely just to fool EzBlocker, lol.

Here's hoping for a fix being in the works, Spotify is literally unuseable without EzBlocker

**Comment by tobiaszHelmud** [comment]
@thatguy344 why don't you just buy Spotify Premium then?

**Comment by thatguy344** [comment]
> 
> 
> @thatguy344 why don't you just buy Spotify Premium then?

Are you serious or just trolling? None of us would be using EZBlocker in the first place or commenting here if we'd be willing to go "Premium". I mean come on, it's the whole reason this project exists in the first place.

**Comment by Werve** [comment]
it seems enough to copy the old .spa files to work again

**Comment by beppe9000** [comment]
did you try with an older build of ezblocker ?

**Comment by Werve** [comment]
> did you try with an older build of ezblocker ?

me? no just replace C:\Users\<username>\AppData\Roaming\Spotify\Apps with an old one (backup). spotify will be the last version and ezblock will work too.

**Comment by beppe9000** [comment]
i tried re-installing an old version... no luck with that. maybe it was too old.

anyways I saw the last commit removed the patching... is EZBlocker muting only now ?

Anyways the final solution is host blocking but it comes with the choice between radio stations and adblocking since they are served from the same domain.

**Comment by Xeroday** [comment]
The blank window issue affects some on the older version of EZBlocker. The newest version won't have this issue.
