### ISSUE TITLE
Spotify notshowing controls when ezblocker attached

### ISSUE THREAD

**Issue by CzBuCHi** [Xeroday/Spotify-Ad-Blocker#186]
Whe EZBlocker is running spotify app show only black screen - as when starts but before controls fade in - im guessing they added some code, that is detecting your code and when detected they do not show any controls ...

Tried downgrade to 1.0.80 but it didnt help ...

Only way to get spotify working again is to click "remove from spotify" and then restart spotify.
but if ezblocker is still running, then spotify gets restarted into "black screen mode" after 10 seconds ...

**Comment by blackwhattack** [comment]
Same here. I don't know how to get it working though. What I did is I reinstalled Spotify, which fixed the problem until I restarted EZBlocker which made Spotify restart and start showing just the blank page on startup.

**Comment by beppe9000** [comment]
I think some js fails, bringing down the entire app

**Comment by Jakub-Svoboda** [comment]
I have encountered the same problem on 2 PCs running windows 10. Whenever I launch ezblocker with spotify, it doesn't show the controls at all and I have to reinstall spotify to make it work again. Then when I launch ez blocker, it kills it again.

**Comment by Xeroday** [comment]
The latest EZBlocker shouldn't have this problem.
