### ISSUE TITLE
Problems starting successfully and not connecting to Spotify

### ISSUE THREAD

**Issue by ArekZajac** [Xeroday/Spotify-Ad-Blocker#187]
When I start EZBlocker I get an unhandled exception error window. This error can be seen here: https://pastebin.com/CmhU47Ka If I press 'Continue' The program launches but forever says 'Loading...' at the bottom - even if I restart Spotify.

Running Spotify version: 1.0.94.262.g3d5c231c

**Comment by Xeroday** [comment]
Can you try running the latest version? Seems like you were on 1.7.2.5.
