### ISSUE TITLE
Disable the startup update checks by default

### ISSUE THREAD

**Issue by i1u5** [Xeroday/Spotify-Ad-Blocker#189]
Whenever I boot the pc with startup enabled on EZBlocker, it throws "Error checking for update.", which becomes annoying by time.

https://github.com/Xeroday/Spotify-Ad-Blocker/blob/88acf24684c1b260f6715d2de2be87bd15412029/EZBlocker/EZBlocker/EZBlockerMain.cs#L162

I kindly ask you to remove that specific line or at least make us able to turn it on/off.

**Comment by DooMl** [comment]
Update : Now it crashes instead of checking, even on the same routine.

**Comment by tricolon** [comment]
> Whenever I boot the pc with startup enabled on EZBlocker, it throws "Error checking for update.", which becomes annoying by time.
> 
> https://github.com/Xeroday/Spotify-Ad-Blocker/blob/88acf24684c1b260f6715d2de2be87bd15412029/EZBlocker/EZBlocker/EZBlockerMain.cs#L162
> 
> I kindly ask you to remove that specific line or at least make us able to turn it on/off.

I have the same problem
