### ISSUE TITLE
Release Radar/Discover Weekly playlists won't refresh properly

### ISSUE THREAD

**Issue by Bukethead** [Xeroday/Spotify-Ad-Blocker#193]
Whenever the Release Radar or the Discover Weekly playlists refresh for the week, my desktop app only loads in 1-4 songs randomly, and the solution as suggested by Spotify, is to reinstall the client. This fixes the issue but only for that instance of the playlist, when it refreshes again I have the same issue.

I don't know if this is being caused by ezblocker or if it's just my client.

**Comment by Foas** [comment]
Having the exact same issue.

**Comment by Bukethead** [comment]
> 
> 
> Having the exact same issue.

It turns out ezblocker adds a hosts file entry, if you remove it your spotify should work as normal again.

**Comment by jaybird565** [comment]
Where would I find and remove this?

**Comment by Bukethead** [comment]
> 
> 
> Where would I find and remove this?

C:\Windows\System32\drivers\etc

it's your hosts file. Open it with a text editor and look for the spotify specific link. Delete that line and save the file.

**Comment by Xeroday** [comment]
Which host is it? EZBlocker doesn't block any spotify urls. It may have in past version or you may have been using other tools.

**Comment by Bukethead** [comment]
You are correct, it was an unrelated issue with my hosts file.
