### ISSUE TITLE
Tried uninstalling completely. Spotify is still muted.

### ISSUE THREAD

**Issue by s-fong** [Xeroday/Spotify-Ad-Blocker#196]
Songs were not playing and everything was blacked out. I followed the steps listed in 
[https://github.com/Xeroday/Spotify-Ad-Blocker/issues/182](url)
to try and completely remove EZBlocker, but Spotify is still muted (even after uninstall reinstalling Spotify). 
Are there other things to change?
I'd rather listen to songs + ads, than nothing at all!
Thanks, Shelley

**Comment by s-fong** [comment]
I fixed it! 
Open Volume mixer, scroll to find the Spotify program, and unmute it.

**Comment by mkeroppi** [comment]
This has been a bug in the program.

**Comment by SoloOrchid** [comment]
dont think this is a bug spotify knows about the application and this happens me from time to time, try using a deezer ad blocker they will send u an email telling you that they know you are running ad blockers on their app...
