### ISSUE TITLE
EZBlocker has completely stopped blocking ads

### ISSUE THREAD

**Issue by Bukethead** [Xeroday/Spotify-Ad-Blocker#208]
EZBlocker no longer mutes ads when they play, making the application useless in its current state. I noticed that in the EZBlocker window, it says "Playing:" with no indication of what is playing, be it an ad or a song.

**Comment by Tiagomfsantos** [comment]
It's working fine in my pc. try run as admin and see if it works. Do not use the windows store app. I have spotify version 1.1.10.540.

**Comment by Bukethead** [comment]
> 
> 
> It's working fine in my pc. try run as admin and see if it works. Do not use the windows store app. I have spotify version 1.1.10.540.

Ah that seems to have fixed it. Thank you.
