### ISSUE TITLE
Crashing after few ads

### ISSUE THREAD

**Issue by N3ars** [Xeroday/Spotify-Ad-Blocker#234]
Everything is in the title, but it doesnt crash on the first ads but later
I had to restart it everytime, is there any way to get the logs to know why this happening?
Thanks.

**Comment by Marcostox** [comment]
Hello, the reasons can be many.
I advise you NOT TO USE spotify windows store version, and keep the ezblocker client up to date. Try reinstalling Spotify. In order not to diminish the influence of third-party programs on EzBlocker I recommend that you start it as an administrator.

**Comment by N3ars** [comment]
Thanks for reply, i do have binary spotify installed, ezblocker is up to date, i did reinstall spotify and i start it as admin, sometimes it crashs now but only when i listen for long time, it's fine tho atleast it did block some annoying ads in the middle of the music ...
