### ISSUE TITLE
Completely mutes all of my songs

### ISSUE THREAD

**Issue by ch1ck3n-byte** [Xeroday/Spotify-Ad-Blocker#237]
I installed EZBlocker yesterday, and it worked fine. But then, the next day, it COMPLETELY mutes all of my songs. How do I fix this?

**Comment by Marcostox** [comment]
Hi, probably when you closed spotify, you did it while an advertisement was playing, in that case EzBlocker mutes the spotify client. When you reopen spotify, just go to the windows mixer and activate the audio to that application.

**Comment by ch1ck3n-byte** [comment]
Oh, thanks
