### ISSUE TITLE
Not exactly an issue, just a suggestion

### ISSUE THREAD

**Issue by DO-Ui** [Xeroday/Spotify-Ad-Blocker#245]
In spotify (at least in the windows store version) i noticed a spotify bug that allows you to compleatly skip the ads simply by closing and re-opening spotify. Perhaps there could be like an experimental option to allow u to do that in the settings. ¯\_(ツ)_/¯

**Comment by DO-Ui** [comment]
I know this is open source but i dont know c# so uh

**Comment by pomonella01** [comment]
The main issue with this is that restarting the process takes longer since there's no reload function (that i'm aware of) built into uwp, but it does exist on electron

**Comment by pomonella01** [comment]
took you this long to close this??
