### ISSUE TITLE
Distributed Block  List

### ISSUE THREAD

**Issue by jstrength** [Xeroday/Spotify-Ad-Blocker#25]
What do you guys think about having a distributed model for the block list so that it is never out of date. The problem with having a static list on xeroday's website is that if he doesn't update it then we all have to manually add new ads to our list. If we could have a small server that serves the block list and listens to new block requests we could then count how many block requests we've gotten, say we get three requests to block the same ad from three unique computers then we will add that to the block list and everyone gets the updated block list(this prevents people from blocking legit songs). I don't think this would be very difficult to implement, just wanted to get everyone's opinion and thoughts about the idea.

Thanks

**Comment by Xeroday** [comment]
#37
