### ISSUE TITLE
Blocker stopped working (Spotify not found)

### ISSUE THREAD

**Issue by Zedruc** [Xeroday/Spotify-Ad-Blocker#263]
The title says everything, EZBlocker does not find Spotify.
EZBlocker Version: 1.8.1.0
Spotify Version: 1.1.80.699

**Comment by mendelsphotography** [comment]
Look At #261 this is a duplicate

**Comment by mendelsphotography** [comment]
@Zedruc

**Comment by mendelsphotography** [comment]
Also #262 That Might be a fix for what your having

**Comment by Zedruc** [comment]
@mendelsphotography downgrading to 1.7.6 also fixes the issue for some reason, really odd

**Comment by mendelsphotography** [comment]
that Nobody said or tried If I had to Guess It's because in the last version it was redone how the muting... Works Which might have to do with the way it was coded.

**Comment by mendelsphotography** [comment]
that's the way it work in code you don't ask to many questions on bugs
