### ISSUE TITLE
Spotify Not Found

### ISSUE THREAD

**Issue by RecordTheRecordian** [Xeroday/Spotify-Ad-Blocker#268]
EZBlocker Version: 1.8.1.0
Spotify Version: 1.1.84.716

Spotify Cannot be found and ezblocker will not mute ads 
![image](https://user-images.githubusercontent.com/104863072/166523548-99945806-98d6-4894-9831-b61f5f00debd.png)

**Comment by mendelsphotography** [comment]
#261

**Comment by RecordTheRecordian** [comment]
ty
