### ISSUE TITLE
Constant not responding app

### ISSUE THREAD

**Issue by silentw** [Xeroday/Spotify-Ad-Blocker#30]
I'm running Windows 8.1 x64 and the current version (V 1.4 (November 22, 2014)) is constantly not responding, resulting in some times the mute feature keeps Spotify muted for a while and then when it unfreezes, it just unmutes Spotify in the middle of a song.

Fallback to the previous version until this is fixed.

Thanks!

**Comment by Xeroday** [comment]
Can someone check if this issue is still exists with Spotify 1.0.1 and EZBlocker 1.5?

**Comment by silentw** [comment]
For now it is working OK, thanks!
