### ISSUE TITLE
Bug: Pausing And Un-pausing Foobar2000 Instead Of Spotify

### ISSUE THREAD

**Issue by war59312** [Xeroday/Spotify-Ad-Blocker#31]
Hey,

So Spotify was playing an ad and I just happended to have Foobar2000 1.3.5 on Win 8.1 x64 open as well, but paused.

Oddly enough Foobar2000 started to be paused and un-paused many times. Turns out it was EZBlocker doing it.

Whoops! Of course it should not be doing anything to Foobar2000 since of course it's just for Spotify. I kinda laughed out loud cause I thought it was going crazy for a second.

Thanks,

Will

**Comment by karlding** [comment]
I experienced this issue today as well. Spotify was playing, and Foobar was open, but paused (with the Media Library Search panel open). Somehow, both Foobar and Spotify began playing simultaneously. I'm not sure if there was an advertisement, like Will noted, as I had left the room moments prior.

EZBlocker was hidden to the system tray (with Taskbar Notifications disabled), and Foobar and Spotify were both minimimzed, with Google Chrome in the foreground. I'm running Windows 8 x64.

**Comment by Xeroday** [comment]
Should be fixed with 1.5.
