### ISSUE TITLE
Make it part of spotify program

### ISSUE THREAD

**Issue by MoBadawy** [Xeroday/Spotify-Ad-Blocker#32]
I asking for EZBlocker be a part of spotify  itself  , can it be an extension or patch for spotify  program and the option show in any where in spotify , In short I want the EZBlocker and spotify be one program . it's will be great, thank you

**Comment by Xeroday** [comment]
Patching or Dll injecting into Spotify requires too much effort in upkeep. EZBlocker is non-intrusive for now.
