### ISSUE TITLE
Even when minimized to the system tray you can switch to it by Alt+Tab

### ISSUE THREAD

**Issue by Konstamokh** [Xeroday/Spotify-Ad-Blocker#36]
Sometimes I accidently switch to EZBlocker, because it's visible while using Alt+Tab. I'd like to have it in the background, so this is a bit annoying.

**Comment by war59312** [comment]
See: https://github.com/Xeroday/Spotify-Ad-Blocker/pull/29

**Comment by Xeroday** [comment]
Currently not implementing #29 because it also removes the minimize button on EZBlocker.

**Comment by Georgeto** [comment]
See #46 for proper solution that does not remove the minimize button.

**Comment by Xeroday** [comment]
Merged #46.
