### ISSUE TITLE
Sort Blocklist

### ISSUE THREAD

**Issue by karlding** [Xeroday/Spotify-Ad-Blocker#37]
Could there perhaps be some way of ordering/filtering the blocklist? I know it's probably not an important feature, since most users won't be spending much time accessing the blocklist &mdash; however, it would make searching for entries that were accidentally added much easier (but you didn't notice until much later).

I believe that currently, the entries are sorted by date (with the newest entry first)? While this is fine if you realize right away what you've done, if multiple advertisements have come up after, that legitimate artist has been buried in oblivion.

Pressing the first letter of the entry allows you to cycle through all entries starting that letter, but a filter view would certainly be nice!

**Comment by Xeroday** [comment]
Blocklists are removed in version 1.5. Closing for now.
