### ISSUE TITLE
TROJAN.MSIL.gen.18 detected in binary

### ISSUE THREAD

**Issue by javaknight** [Xeroday/Spotify-Ad-Blocker#40]
https://www.virustotal.com/en/file/fb41741429f29f778ea92998129c957adcd60d6b498a06140ead27395e9d2b44/analysis/1425917307/

**Comment by Xeroday** [comment]
If you're going to believe that EZBlocker is malware based on the fact that 1/57 AVs say it is, compile it yourself.

**Comment by war59312** [comment]
Like he said, it's called a "false postive" mate.
