### ISSUE TITLE
Some ads are missed by EZBlocker

### ISSUE THREAD

**Issue by harangue** [Xeroday/Spotify-Ad-Blocker#42]
Previously this was not an issue due to the presence of a block-list. Now I'm getting around a 10% failure rate with muting ads. Next time I experience the problem I'll check for the specific ads themselves.

EDIT: I checked my history and the ads "Pennsylvania College of Arts & Design" and "Trance Top 1000" were not blocked.

**Comment by commonquail** [comment]
I'm experiencing an issue where at least some video ads (are these "banner ads"?) are missed. The banner ad setting is enabled. I don't know if all video ads are missed or whether the block-list version would catch them, only that the ones that do get missed are really obscenely loud and are actually the primary reason for wanting to block ads to begin with.

This is release 1.5 on Windows 7.

**Comment by djprmf** [comment]
I'm using the version 1.5.1.4 of EZBlocker (with Spotify 1.0.1.60), and most of the times the audio ads also doesn't get muted.
The EZBlocker shows the ad in the info, and the Mixer actually appears to be "muted", but the audio still outputs...

**Comment by Xeroday** [comment]
Can someone provide any screenshots with an ad playing on Spotify and what the EZBlocker says?

**Comment by insurw** [comment]
I've checked and for me the ads aren't blocked because EZ sometimes seem to get stuck on "Spotify is paused", both when playing ads and songs. So in my case it's got nothing to with ad detection.

**Comment by J4G-** [comment]
Likewise for me.

**Comment by insurw** [comment]
I thought EZ getting stuck on pause was because I ran EZ from a network drive. But it doesn't help to run from a local drive. I guess the one reason could be that EZ can't handle Win7's sleep properly? At least when the PC has been sleeping for a while, e.g. 30 min or something. Putting PC to sleep a couple min then resuming doesn't seem to affect EZ.

**Comment by J4G-** [comment]
I get the issue in two cases.
1. Whenever I start EZBlocker, on occasion
2. After long periods of idling (not sleep)
