### ISSUE TITLE
Did Spotify Update?

### ISSUE THREAD

**Issue by SkiingxMoose** [Xeroday/Spotify-Ad-Blocker#43]
My spotify restarted, and now EZ Blocker doesn't work. The spotify version listed in my client is 1.0.1.1060.gc75ebdfd

**Comment by kevonh** [comment]
It would appear that spotify did update and the auto-blocking no longer works. The mute button works, but EZBlocker no longer detects what is playing.

Is Xeroday still maintaining this?

**Comment by kevonh** [comment]
I just updated to the latest (didn't realize I didn't have it) and it works as advertised.

**Comment by SkiingxMoose** [comment]
Oh I know why I didn't notice this. Version 1.5 is listed as having been released in March 2014, not 2015. I saw that and assumed I already had the latest version. Thanks @kevonh
