### ISSUE TITLE
Windows XP support

### ISSUE THREAD

**Issue by acters124** [Xeroday/Spotify-Ad-Blocker#47]
Ok...
I understand that Microsoft has stopped support for Windows XP.

However, This old monster was around since late XP and early Vista inquisition.
I am unable to earn enough funds to put aside to upgrade my machine to a more modern one.
I request through your kindness to program a Spotify Blocker that will work on Windows XP.
Windows vista and greater haven't shown any bright signs for me to permanently upgrade without slowing down inexplicably.
you are my only hope... :'(

**Comment by Xeroday** [comment]
Sorry, Windows XP has too many issues. You can try using an older version of Spotify (0.9) with EZBlocker 1.2, which had XP support.

**Comment by acters124** [comment]
Thanks for your consideration.
