### ISSUE TITLE
Improvement: Start minimized

### ISSUE THREAD

**Issue by SjoerdvGestel** [Xeroday/Spotify-Ad-Blocker#48]
Hi Guys!

Love the tool! 
Only thing missing is a toggle to start minimized.
It now always opens up fully when started and (for my work machine) it freezes for a minute or so. in this periode im unable to minimize it. Only after it unfreezes am i able to minimize to sytem tray.

Keep up the great work!

**Comment by ch0rn** [comment]
I have same issue, it works once it unfreezes just fine, but sometimes that can take 5 minutes where it is sitting "unresponsive".    This only happens on 1 of my computers.  (It still works, just looks frozen)

**Comment by war59312** [comment]
+1 Should be default.

**Comment by Flaff** [comment]
You can just make an app shortcut and in properties select "Start minimized" from droplist for now. :)

**Comment by Xeroday** [comment]
v1.6.7 will start minimized if you set EZBlocker to open automatically on startup.
