### ISSUE TITLE
Banner ads are blocked, but container remains

### ISSUE THREAD

**Issue by pennstatephil** [Xeroday/Spotify-Ad-Blocker#49]
While the banner ads are blocked, the container it's in remains and can't be removed/resized, blocking a LOT of screen real estate. The workaround I've found is restarting spotify, which is obviously not ideal. I'll post a screenshot as soon as I see this behavior again.

Great tool, you wooed me away from blockify ;)

**Comment by Xeroday** [comment]
EZBlocker only prevents ads from being loaded, but does not remove the containers that Spotify reserves for display ads.

**Comment by pennstatephil** [comment]
would you consider it as an enhancement request? blockify was able to do this... either way, thank you for your work on this.
