### ISSUE TITLE
Infinity showing error dialog

### ISSUE THREAD

**Issue by D-Ogi** [Xeroday/Spotify-Ad-Blocker#50]
![screenshot_35](https://cloud.githubusercontent.com/assets/6542335/7217482/a6797ac0-e62d-11e4-808f-c478dd0acb36.png)

I've also no idea how to "allow spotify to be started from the Web".

**Comment by cgarst** [comment]
Make sure you can execute %APPDATA%\Spotify\SpotifyWebHelper.exe. Mine was blocked by software restrictions policy which caused this.

**Comment by Ineluctable** [comment]
I had the same issue (20+ popups with the mentioned error message), and I ended up having to kill the program with task manager.

cgarst's solution is correct. I use CryptoPrevent which had an overzealous restriction policy. After whitelisting the path he specified ( %APPDATA%\Spotify\SpotifyWebHelper.exe ) the program loads without the popups.

**Comment by D-Ogi** [comment]
Thank you both. It was about CryptoPrevent in my case too. It's working fine now (except small issue, freezing after closing Spotify).
