### ISSUE TITLE
Now Playing doesn't support unicode

### ISSUE THREAD

**Issue by coin3x** [Xeroday/Spotify-Ad-Blocker#51]
Now Playing doesn't support unicode
![default](https://cloud.githubusercontent.com/assets/9127594/7390520/ae7e109c-eeab-11e4-84a4-57668b2810ef.PNG)

**Comment by Xeroday** [comment]
I'm using UTF-8. I'm guessing you're talking about other languages? The now playing text in EZBlocker doesn't relate to the ad blocking functionality, so it's not a priority.
