### ISSUE TITLE
New Spotify version 1.0.4 not supported

### ISSUE THREAD

**Issue by Boia11** [Xeroday/Spotify-Ad-Blocker#52]
![screenshot 2015-05-03 14 01 05](https://cloud.githubusercontent.com/assets/10048197/7444960/61851106-f19d-11e4-9b07-8bed73174110.png)
With new version of Spotify 1.0.4.90 & EZBlocker 1.5.1.4 the music was not detect

**Comment by Xeroday** [comment]
Have you tried restarting EZBlocker? I can't test it at the moment.

**Comment by Boia11** [comment]
Yes with admin permission

**Comment by SjoerdvGestel** [comment]
I have no issues with it
![untitled-1](https://cloud.githubusercontent.com/assets/1597644/7515971/f4e69f6a-f4cb-11e4-88e1-e6daf2710a1a.jpg)

**Comment by Boia11** [comment]
I try again and it work only for one time but after pause and restart song, EZ stop to trace the song.
I have try to disable Kaspersky Internet Security for test but it's not this the problem.
How can I help you to find a problem?

**Comment by Boia11** [comment]
How to keep an debug log of execution of application? @Xeroday

**Comment by Xeroday** [comment]
There's not much debug output other than the Playing: text on the main window. If there's an error, a stack trace will be output to an error log in the same directory as the EZBlocker executable.

**Comment by Boia11** [comment]
I have found the problem...EZ-Blocker don't track music when i put Spotify into Private Session. Can you fix it?

**Comment by Xeroday** [comment]
#53
