### ISSUE TITLE
Not working on Private session

### ISSUE THREAD

**Issue by GregorAP** [Xeroday/Spotify-Ad-Blocker#53]
As title says: the blocker isn't working on private sessions. Aside from that, awesome work!

Thanks for the great app!

**Comment by Xeroday** [comment]
I will probably work on something to block ads on private browsing. At the moment, EZBlocker will notify you if you're on a private session.

**Comment by GregorAP** [comment]
Thank you!

**Comment by Xeroday** [comment]
Version 1.7 supports private sessions.
