### ISSUE TITLE
Avira reporting virus

### ISSUE THREAD

**Issue by tompazourek** [Xeroday/Spotify-Ad-Blocker#57]
Today, my Avira started reporting EZBlocker as a security threat:

![capture](https://cloud.githubusercontent.com/assets/370699/9377690/af9089ec-471b-11e5-82bc-86aa4c0d649c.PNG)

Probably false alarm:

https://virusscan.jotti.org/en-US/filescanjob/jzabmvzmpo

**Comment by Acters** [comment]
Confirmed as false alarm.

What could maybe trigger this is the writing of the HOSTS file or something else entirely.
However this is completely harmless as it seems Avira and other less know virus scanners are discerning EZBlocker as a trojan, albeit "harmless".

virustotal:
https://www.virustotal.com/en/file/46c0629238fadf972d8af3760702a2cdb2c92dcf543f224449f29e41aef5274a/analysis/

**Comment by tompazourek** [comment]
When I launch the EZBlocker, I launch it without administrator privileges, so it doesn't actually write to the hosts files. If I launch it with the privileges, I get a whole other notice from Avira about not allowing the program to write to hosts file.

But the antivirus might just detect that the program as Trojan by various heuristics, maybe presence of path to the host file and some other dll references add to some weighing which will end up as false alarm for some virus scanners.

**Comment by Acters** [comment]
This are the changes to the HOSTS file that EZBlocker does:
https://github.com/Xeroday/Spotify-Ad-Blocker/blob/e878d57652aed654f69ceeda219d0777f43bed6d/EZBlocker/EZBlocker/Form1.cs#L416-L421
This is harmless and not an issue.

**Comment by Xeroday** [comment]
FAQ updated on EZBlocker page. As others have said, it's most likely due to the hosts file stuff.
