### ISSUE TITLE
Stopped working since Spotify 1.0.18.60

### ISSUE THREAD

**Issue by Jiia** [Xeroday/Spotify-Ad-Blocker#65]
Ad blocking doesn't work anymore. Banner ads haven't been blocked for a long time but after the latest update to Spotify even the radio ads are not blocked anymore.

**Comment by ilbonte** [comment]
A temporary solution could be [blocking spotify updates](https://community.spotify.com/t5/Help-Desktop-Linux-Windows-Web/Tutorial-stop-auto-update-and-use-old-client-and-skin/td-p/769659)

**Comment by leandroprz** [comment]
I'm experiencing the same issue. Looks like we'll have to go back to an older version in the meantime.

**Comment by djprmf** [comment]
Everything appears to be working fine here...
Last version of Spotify installed and music ads still being blocked...

**Comment by lukehsiao** [comment]
Everything is also working fine for me on Spotify 1.0.20.94.

**Comment by MrRafalSzymanski** [comment]
Spotify 1.0.23.90.g42187855
Music Ads are not blocked anymore.

**Comment by ilbonte** [comment]
Sorry guys but I think that these issues and comments are pointless.
@Xeroday didn't have any activity in the last few months neither here or on his blog, so I think that he is not interested in this project anymore. If you have issue with this version you should check out the forks (https://github.com/Xeroday/Spotify-Ad-Blocker/network) and see if one suits your needs.

BTW I'm using Spotify 1.0.23.90.g42187855 too and it's working fine for me.

**Comment by ilbonte** [comment]
Sorry guys but I think that these issues and comments are pointless.
@Xeroday didn't have any activity in the last few months neither here or on his blog, so I think that he is not interested in this project anymore. If you have issue with this version you should check out the forks (https://github.com/Xeroday/Spotify-Ad-Blocker/network) and see if one suits your needs.

BTW I'm using Spotify 1.0.23.90.g42187855 too and it's working fine for me.

**Comment by Xeroday** [comment]
I'm actively monitoring almost every Spotify update and so far haven't actually run into any problems w/ EZBlocker. My latest test is on 1.0.23.90 on 64 bit Windows 10, fresh install onto a VM.

**Comment by Xeroday** [comment]
The latest update should notify you when an update breaks EZBlocker and ask you to restart.
