### ISSUE TITLE
Don't work on windows 10

### ISSUE THREAD

**Issue by leknoppix** [Xeroday/Spotify-Ad-Blocker#66]
Hi

I have dicover this program today, but when i want to laught this on windows 10, the program stop immediately

**Comment by methanols** [comment]
It works for me on Windows 10. That's why I wouldn't say it's a compatibility issue but you can try to run it in a compatibility mode.

**Comment by leknoppix** [comment]
with compatibility on windows XP, Vista et seven, the program stop immediately

**Comment by djprmf** [comment]
Did you run it as admin?

**Comment by leknoppix** [comment]
YES and with admin mode compatibility mode.

**Comment by chromerobv** [comment]
doesn't work for me either. start as admin.
bottom of app it says "Connection Error..."

**Comment by chromerobv** [comment]
Ok, scratch that. It works but still says connection error. Also I have to close and restart if I leave it open for a while without listening to music.

**Comment by ilbonte** [comment]
You should try this fork: https://github.com/shadow1runner/Spotify-Ad-Blocker
You have to compile the soure code by yourself though.

**Comment by Xeroday** [comment]
Latest version should fix this. Re-open if it isn't fixed.
