### ISSUE TITLE
Crashing after the latest update

### ISSUE THREAD

**Issue by Zavian** [Xeroday/Spotify-Ad-Blocker#67]
I don't know if it's just me but it seems that the latest update from spotify broke the program. Infact everytime I try to open EZBlocker, spotify just crashes. The same happens both opening spotify with ezblocker and opening first spotify and then ezblocker

![Version 1.0.21.141.g](http://i.imgur.com/KG3MY5j.png)

**Comment by ilbonte** [comment]
@juk47ht See https://github.com/Xeroday/Spotify-Ad-Blocker/issues/65#issuecomment-188947692

**Comment by juk47ht** [comment]
@ilbonte cheers for this. After seeing that comment, I gave it an another go to (first start Spotify and then Ezblocker) and it worked with the latest Spotify version.

**Comment by Xeroday** [comment]
Latest update should notify you when it's stuck and restart.
