### ISSUE TITLE
No block the banners on new version please update it!!

### ISSUE THREAD

**Issue by Dexterlab1** [Xeroday/Spotify-Ad-Blocker#68]
**No block the banners on new version please update it!!******

**Comment by Xeroday** [comment]
Could you take a screenshot? Are they "Upgrade to Premium" banners?

**Comment by Romaryho** [comment]
Today 18th March 2016
![s version](https://cloud.githubusercontent.com/assets/17924819/13874359/2019aeca-ed00-11e5-8e0d-310ddf4488ea.png)
![spotify](https://cloud.githubusercontent.com/assets/17924819/13874360/20380866-ed00-11e5-9329-f12d5ed9705a.png)

**Comment by Xeroday** [comment]
Latest should block. This is also an experimental feature so it may not work after a Spotify update.
