### ISSUE TITLE
Spotify is not running. Please restart EZBlocker after starting Spotify.

### ISSUE THREAD

**Issue by chromerobv** [Xeroday/Spotify-Ad-Blocker#70]
downloaded newest version. this comes up seconds after starting. with spotify running. and sometimes it even says "spotify paused" in ezblocker.
also if i start ezblocker before i open spotify it opens spotify for me and still comes up with error.

sometimes another box comes up with this error:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: The server committed a protocol violation. Section=ResponseStatusLine
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at EZBlocker.WebHelperHook.GetPage(String URL)
   at EZBlocker.WebHelperHook.SetCSRF()
   at EZBlocker.WebHelperHook.GetStatus()
   at EZBlocker.Main.MainTimer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1063.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
EZBlocker
    Assembly Version: 1.6.0.0
    Win32 Version: 1.6.0.0
    CodeBase: file:///D:/Prog/EZBlocker/EZBlocker.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
CoreAudio
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///D:/Prog/EZBlocker/CoreAudio.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.2.19309
    CodeBase: file:///D:/Prog/EZBlocker/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by yTallBalls** [comment]
+1 - Having the same issue

**Comment by mmoura11s** [comment]
Having the same issue

**Comment by Xeroday** [comment]
I've updated EZBlocker to try to fix this issue. Could you please redownload and let me know if it works?

If not, can you check that "Allow Spotify to be started from the web" is enabled in your Preferences -> Advanced settings?

**Comment by yTallBalls** [comment]
Eric,

Thanks for the updated file but I am still running into the same issue. After a couple of minutes starting ezblocker, I get prompted with the message. I have verified and "Allow Spotify to be started from the web" is enabled in Preferences.

Let me know if you need any additional info.

**Comment by Xeroday** [comment]
Do you see a log file created in the same folder as EZBlocker.exe? If so, could you please post its contents?

And which Windows version are you using?

**Comment by yTallBalls** [comment]
Unfortunately, there is no log file. Let me know if there is a way to force
the file to be created and I will be more than happy to reproduce it for
you.

Windows 7 Pro x64
.NET Framework  4.6.1

**Comment by Xeroday** [comment]
I've just tested on a VM with the same Windows & .NET versions and still can't seem to reproduce. Can I send you a debug version of the app sometime for you to run? It will output all the steps the app is taking.

And does EZBlocker work for a few minutes before it crashes or does it just hang for a minute after you open it and then crash. Could you take a screenshot of the error it gives when EZBlocker crashes?

Thanks for the help so far.

**Comment by yTallBalls** [comment]
Absolutely! Send it my way!

EZBlocker seems to work for about a minute or so. It opens fine and starts
Spotify, I then minimize it and start playing music through Spotify and it
runs fine. After a minute of two, I get a pop-up dialog box stating,
"Spotify is not running. Please restart EZBlocker after starting Spotify."
EZBlocker seems to crash as it is gone from the system tray and causes
Spotify to hang as I cannot stop the music. If I close Spotify (by clicking
on the X, not force close through Task Manager), Spotify will close but
music will still play for up to a minute.

Hope that helps.

**Comment by Xeroday** [comment]
Could you try with this? It should create a EZBlocker-log.txt file if things go wrong. Could you post the contents when EZBlocker runs into issues?

[EZBlocker.zip](https://github.com/Xeroday/Spotify-Ad-Blocker/files/169969/EZBlocker.zip)

**Comment by yTallBalls** [comment]
Different this time. No longer getting the pop-up box with the error. This
time getting a balloon dialog stating, "Error connecting to Spotify.
Retrying..."

Contents from the log only contain one message over and over again:

"The operation has timed outNot running."

EZBlocker 1.5 still works fine for me and produces no errors (just for a
comparison)

**Comment by yTallBalls** [comment]
![ezblocker balloon message](https://cloud.githubusercontent.com/assets/17784943/13715811/d83f6558-e79c-11e5-8a4a-9430f613a5bd.jpg)

**Comment by Xeroday** [comment]
Does version 1.5 correctly get the name of the artist when you're playing on Spotify?

Could you also try this version and post the log if errors occur?

[EZBlocker.zip](https://github.com/Xeroday/Spotify-Ad-Blocker/files/170007/EZBlocker.zip)

**Comment by yTallBalls** [comment]
I normally run Spotify minimized so I haven't noticed. When I do maximize
it, it always shows the correct song that is playing (but I will pay more
attention and keep you posted). To be honest, 1.5 works great for me and I
only upgraded because I was prompted today when I started EZBlocker. I
normally run EZBlocker (v.1.5)/Spotify for hours everyday and never have a
problem with it.

Been running version 1.5 for about 15 minutes now and no log file and
everything is working fine. Will update when/if a log is created.

Let me know if there is anything else you want me to test with 1.6.x. I
don't mind testing/debugging for you.

**Comment by yTallBalls** [comment]
Oops... I didn't see the new version you uploaded... I will try it now.

**Comment by yTallBalls** [comment]
OK, same balloon dialog appears as before after about one minute of starting Spotify. 

The entry in Log file repeats with the same two messages:
-----------------------------------------------------------------------
WebHelperHook: The operation has timed out
Not running.
WebHelperHook: The operation has timed out
Not running.

**Comment by Xeroday** [comment]
Could you go to http://127.0.0.1:4380 and let me know if it loads? That's the page EZBlocker is timing out on.

I think the same issue is happening on 1.5 but there's just no alerting on it. Do you have "Block banner ads" enabled?

**Comment by yTallBalls** [comment]
I get "Not Found". See image

![notfound](https://cloud.githubusercontent.com/assets/17784943/13717400/d6bc1834-e7a6-11e5-9da5-5bad54197190.jpg)

**Comment by yTallBalls** [comment]
I do have block banner ads enabled but when I try to access that link running Spotify w/o running EZBlocker it get the same message.

For fun, I disabled blocked banner ads and got the same message posted above (Not Found)

**Comment by Xeroday** [comment]
Do you recall how long it took to load that page? What's happening is that it's taking EZBlocker more than 5 seconds to load it. Could you try this build? It increases the timeout from 5 seconds to 20. I believe EZBlocker 1.5 had it for 60 seconds.

[EZBlocker.zip](https://github.com/Xeroday/Spotify-Ad-Blocker/files/170129/EZBlocker.zip)

**Comment by yTallBalls** [comment]
The page loaded quickly previously. No delays of any kind loading.

I am trying the new exe now and let you know the results.

**Comment by yTallBalls** [comment]
With the new exe,  127.0.0.1:4380 loads quickly (as before). After about a minute of starting, same balloon dialog pop-up appears and same errors in the logs:

[EZBlocker-log.txt](https://github.com/Xeroday/Spotify-Ad-Blocker/files/170136/EZBlocker-log.txt)

**Comment by Xeroday** [comment]
Once the popups start, how often do they re-appear? Are they constant or do they come about once a minute?

**Comment by yTallBalls** [comment]
Previously they were constant.

With the last exe was about every 20 seconds.

**Comment by Xeroday** [comment]
Ok last build before I'm actually out of ideas. I completely reverted the way EZBlocker grabs the song data back to v 1.5. Could you delete the log file before starting it and let me know how it goes?

[EZBlocker.zip](https://github.com/Xeroday/Spotify-Ad-Blocker/files/170172/EZBlocker.zip)

**Comment by yTallBalls** [comment]
That change is working for me.  Been running now for about 10 minutes and no errors being displayed or in the logs.

Will keep running EZBlocker (1.6.3) and Spotify (1.0.24.x) and let you know if anything changes.
