### ISSUE TITLE
Drop The "EZBlocker is hidden" Balloon Tip

### ISSUE THREAD

**Issue by war59312** [Xeroday/Spotify-Ad-Blocker#71]
Hi,

Please drop the "EZBlocker is hidden" Balloon Tip. So annoying.

Or at least make it so that if I click the balloon tip it's never shown again.

See: https://github.com/Xeroday/Spotify-Ad-Blocker/pull/73

Thanks,

Will

**Comment by optical** [comment]
Agree with this sentiment, should be toggle-able imo.

**Comment by Xeroday** [comment]
How often do you minimize EZBlocker such that the balloon tip gets annoying? I'll probably update it to only show once on every launch.

**Comment by szmaorka** [comment]
Notification Bar -> right clik on the notification -> Turn Off for this app ;)
