### ISSUE TITLE
System Tray (Notification Area) Icon Suggestions

### ISSUE THREAD

**Issue by war59312** [Xeroday/Spotify-Ad-Blocker#72]
Hi,

If EZBlocker is open on screen and I double click its System Tray (Notification Area) Icon, it should be hidden.

Should put a tooltip on the icon as well. So if I mouse over its icon it should say "EZBlocker".

Add a basic context menu (right click) to the icon.

I suggest having:

> Open (Switch to Close if open on screen)
> About (Have a nice about screen)
> Exit

Double right-clicking icon should do nothing (besides make context menu display twice). Currently, it causes it to open on screen.

All of this is pretty much standard design guidelines.

A nice thing to have would be for a single left click on its icon to show a notification (Artist> Title) of the current song playing.

Thanks,

Will

**Comment by Xeroday** [comment]
System tray has been added.
