### ISSUE TITLE
Blocker sometimes closes automatically when playing local files.

### ISSUE THREAD

**Issue by fusobotic** [Xeroday/Spotify-Ad-Blocker#74]
Not too critical but it seems like the blocker closes whenever Spotify hangs for a second trying to access a local file (it took a bit because it was accessing an inactive hard drive). 

Maybe just allow the blocker to stay open even when it detects Spotify being "closed"? I know in the previous version it used to crash whenever you close Spotify first, but I feel like adding a notification and an error popup isn't really fixing the root problem. 

Anyways, thanks for making this, it's super nifty!

**Comment by Xeroday** [comment]
The latest update should work fine with local files.
