### ISSUE TITLE
Possible solution to Spotify crashing with EZBlocker version 1.6+

### ISSUE THREAD

**Issue by dnyplaya** [Xeroday/Spotify-Ad-Blocker#76]
Spotify was crashing for me almost every time I tried to use EZBlocker to open it, until I tried this: 

I went to my EZBlocker application folder, and (1)right clicked on "EZBlocker.exe" then clicked on Properties, (2)then checked the "Unblock" box at the bottom of screen. (3)Then clicked OK, and it worked fine right away.

I may be wrong, or the only one who experienced this problem/solution, but it could be worth a try for some.

<img src="http://i.imgur.com/TaNUnbl.png" alt="Example image" title="Click to enlarge" width="400px">

**Comment by Xeroday** [comment]
Latest version should not cause Spotify to "not respond".
