### ISSUE TITLE
Feature request: New version support for Spotify v.0.9.7

### ISSUE THREAD

**Issue by rkantos** [Xeroday/Spotify-Ad-Blocker#77]
As you and probably many people who still knowo that v0.9.7 of Spotify is still usable, and also in my opinion the best version of Spotify that there is, is still working; I'm hoping the newest version, or at least the currently latest version of 1.6 to be made to support Spotify v0.9.7

For people who do not know v0.9.7 still works: http://www.javiersantos.me/post/82199053318/download-for-win-os-x-turn-back-to-the-previous-spotify

For people who really think anything after v1.1 of Spotify is really better:
https://www.reddit.com/r/spotify/comments/2y6a68

http://i.imgur.com/trieJjq.png

Summary: v1.4 of the ad-blocker seems to work, but it probably wouldn't hurt to have the newest features of the newer version for v0.9.7 of Spotify? So I am at least throwing this out there.

**Comment by Xeroday** [comment]
Older releases should work. Try them here: https://github.com/Xeroday/Spotify-Ad-Blocker/releases
