### ISSUE TITLE
There was an error updating EZBlocker. Please run as administrator to update.

### ISSUE THREAD

**Issue by aampudia** [Xeroday/Spotify-Ad-Blocker#79]
I'm getting this alert everytime i open the new version (1.6.4):

There was an error updating EZBlocker. Please run as administrator to update.

even when i'm absolutely sure it's opening as administrator, i didn't have that issue with the previous version. I even tried the previous version after trying 1.6.4 and it worked just fine.    and i tried in 2 different computers, with same results

**Comment by ilbonte** [comment]
Same error on win10x64 but the program is working without problem

**Comment by Xeroday** [comment]
Have you tried 1.6.5?

**Comment by aampudia** [comment]
well... it wasn't available 20 minutes ago!! xD   yeah, it seems to work!!! at least in one of the computers, in the other one it always says "spotify is paused", i'll try to reinstall spotify and EZBlocker, thank you very much!!!

**Comment by ilbonte** [comment]
Now it is working fine for me! :+1:
