### ISSUE TITLE
Error hooking Spotify. Please restart EZBlocker after restarting Spotify.

### ISSUE THREAD

**Issue by CHEF-KOCH** [Xeroday/Spotify-Ad-Blocker#84]
Hey,
I only found one _issue_ well it's minor but it's a little bit annoying so I think reporting this to possible fixing this would be helpful. 

![spot](https://cloud.githubusercontent.com/assets/727123/15600553/f3e99802-23ea-11e6-9fb1-087e2b345874.png)

I get this popup each time I restart my PC, EZBlocker works well, the thing is just the first start after a reboot/start of the PC since I don't know Spotify starts before EZBlocker? If I manually start EZBlocker (spotify not running) then everything works, it starts Spotify without any popup or something. 

**Even if I not restart EZBlocker it still works fine after the 'error'? Maybe one of this option would help:**
* Implement an option to remove Spotify's own 'autostart' and add EZBlocker instead to avoid this.
* Ensue EZBlocker starts before Spotify if Spotify autostart was detected.
* Or if it's confirmed as still working (I only quick tested it) then simply remove the popup and only show it if it's really related.

![ez](https://cloud.githubusercontent.com/assets/727123/15600686/ddc025d6-23eb-11e6-88cc-fff1f2a49f35.png)

Setup:
* Win 10 x64
* Spotify for Windows 1.0.29.90.g200ff544 up to 1.0.33.106.g60b5d1f0
* EZBlocker 1.6.7

Edit:
Even after I remove the SpotifyWebHelper from system startup it still shows this error.

Thanks :+1:

**Comment by IOMachinery** [comment]
Hi,
I'm not starting EZBlocker on login, but I can observe the same behavior every time I launch EZBlocker first (as opposed to starting Spotify, then EZBlocker).

Starting EZBlocker launches Spotify for Windows, as you would expect, but it fails to hook up with it. I have to manually re-open it instead.

- Win10 x64
- Spotify for windos 1.0.33.106.g60b5d1f0
- EZBlocker 1.6.8

**Comment by codermonkey** [comment]
I had to use a PowerShell Logon in my GPEdit and disable Start on Logon on both EZBlocker and Spotify to workaround this issue. Here's my code:

`$pathSpotify = $env:USERPROFILE + "\AppData\Roaming\Spotify\SpotifyLauncher.exe"`
`$pathEZBlocker = $env:USERPROFILE + "\AppData\Roaming\Spotify EZBlocker\EZBlocker.exe" #Change to your path`
`Start-Process $pathSpotify`
`Start-Sleep -m 3000`
`Start-Process $pathEZBlocker`

**Comment by Xeroday** [comment]
How long does it take for Spotify to open after opening EZBlocker (in seconds)? EZBlocker will now wait up to 12 seconds for Spotify to load.
