### ISSUE TITLE
EzBlocker detected as Virus - False positive!

### ISSUE THREAD

**Issue by CHEF-KOCH** [Xeroday/Spotify-Ad-Blocker#85]
![32323](https://cloud.githubusercontent.com/assets/727123/15781786/fece3292-29a7-11e6-878e-38508227e645.png)

Should I contact them? Or do you want making this?

**Comment by Xeroday** [comment]
I think 1/56 is fine as a false positive rate. Not much I can do. Maybe will get a cert to sign EZBlocker builds later.
