### ISSUE TITLE
Last/pause/next buttons not displayed when Spotify is minimized

### ISSUE THREAD

**Issue by ArKaWu** [Xeroday/Spotify-Ad-Blocker#86]
Sorry if this behavior has to do with the way you skip ads and I didn't read the corresponding FAQ, but I thought that this was a little strange.

When I have access to a keyboard with play/pause button I can pause Spotify's playback when started by your application and I press the pause button on the keyboard.
However if I hover over the minimized app icon the buttons for last/pause/next aren't displayed.
When I start Spotify first and then start your application with administrator rights like normal the buttons are displayed however.
If there is a way to reenable the buttons even if Spotify is started by your application that would be great.

**Comment by Xeroday** [comment]
I don't think this is an EZBlocker issue. EZBlocker doesn't modify Spotify in any way. The hover over icons are still visible for me.
