### ISSUE TITLE
Early Unmute

### ISSUE THREAD

**Issue by codermonkey** [Xeroday/Spotify-Ad-Blocker#87]
Sometimes it unmutes just a second or two before an ad is over; not a big deal, but could use some fine tuning if you're up for it. ;)

On a side note, I'd MUCH prefer this bug than missing part of my songs, so better to unmute a bit early than too late if that's the option we're left with. :D

**Comment by lukehsiao** [comment]
I can confirm this as well running on Windows 10, with EZBlocker version 1.6.8.  I agree with codermonkey, this is just a small bug, but noticeable enough to file here.

**Comment by Xeroday** [comment]
Performance should be better in 1.6.8.2. There's a trade-off b/w EZBlocker using more system resources or being more responsive. Let me know if you're still having the same problem.
