### ISSUE TITLE
Ad does not start or end

### ISSUE THREAD

**Issue by EliuTimana** [Xeroday/Spotify-Ad-Blocker#88]
I have an issue with this ad, initially it **doesn't play**, so when i press the **play** button, it starts to play but when it ends, **spotify not continue playing songs**, and i have to restart spotify.
![image](https://cloud.githubusercontent.com/assets/11860802/18154198/60329ee0-6fc8-11e6-8a22-cacb38f2894a.png)

this happend when i try to play songs
![image](https://cloud.githubusercontent.com/assets/11860802/18154332/549dede0-6fc9-11e6-9da0-29e443c403b7.png)

**Comment by Xeroday** [comment]
EZBlocker should automatically play ads. Are you running other music programs at the same time?

**Comment by Xeroday** [comment]
This is a Spotify issue and unrelated to EZBlocker https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Song-won-t-play-after-ad/td-p/543160
