### ISSUE TITLE
Suggestion : display version of the app 

### ISSUE THREAD

**Issue by theblackhole** [Xeroday/Spotify-Ad-Blocker#89]
Hello,

Is it possible to add the version number on the app (+ link to the website or the github release page ?) ? Like maybe somewhere on the window
![image](https://cloud.githubusercontent.com/assets/7818904/18231697/2b62ca96-72c0-11e6-8f76-d39b76aad57c.png)
or the title bar or maybe by right clicking on the taskbar icon ? (">about" or something like that)

It will be easier to check for updates 😄 

Thanks for your work : this app is awesome ! 😃

**Comment by Xeroday** [comment]
Version numbers are available in the file properties -> Details.
