### ISSUE TITLE
FORCE CLOSES (windows [ERROR]: EZblocker has stopped working)

### ISSUE THREAD

**Issue by Trillx** [Xeroday/Spotify-Ad-Blocker#99]
I open the program then it runs perfectly untill i try to open it in the system tray them i get this 
![capture](https://cloud.githubusercontent.com/assets/20881828/19630655/7b5d96bc-9943-11e6-9582-686a9e02adf4.PNG)

HELP ?

I HAVE ALSO RAN THE PROGRAM AS ADMIN

**Comment by Xeroday** [comment]
Can you post the contents of the EZBlocker-log.txt file?

**Comment by Trillx** [comment]
I could ... But nothing is in it since the force close is automatically

**Comment by Trillx** [comment]
I was able to get This 
[EZBlocker-log.txt](https://github.com/Xeroday/Spotify-Ad-Blocker/files/563453/EZBlocker-log.txt)

**Comment by Xeroday** [comment]
In your Spotify Preferences, can you go to the Advanced Settings and check if "Allow Spotify to be opened from the web" is enabled?

**Comment by Trillx** [comment]
yess sir
![image](https://cloud.githubusercontent.com/assets/20881828/19881698/3451fffa-9fc5-11e6-9a15-f708b4dbf9aa.png)

**Comment by sakshamgoyal01** [comment]
antivirus blocking it?
to to task manager and click details. then right click the process and select analyse wait chain. that should be usefull

**Comment by sakshamgoyal01** [comment]
do this while the thing has 'stopped working'

**Comment by Trillx** [comment]
@sakshamgoyal01  no anti virus not blocking its just not responding ........for example it will run for a good 2min but stop

**Comment by MatrixDJ96** [comment]
Check ezblocker 2

**Comment by Xeroday** [comment]
Newest version should resolve this. Re-open if you're still experiencing it.
